FROM golang:1.20.4 AS build

ARG VERSION
ARG REVISION
ARG BUILDDATE

WORKDIR /src

COPY Makefile go.mod go.sum ./
RUN make download

COPY . .
RUN make clean build VERSION=$VERSION

FROM alpine:3.18.0

WORKDIR /usr/local/bin

COPY --from=build /src/gitlab-ci-semver-labels .

ENTRYPOINT ["gitlab-ci-semver-labels"]

LABEL \
  maintainer="Piotr Roszatycki <piotr.roszatycki@gmail.com>" \
  org.opencontainers.image.created=${BUILDDATE} \
  org.opencontainers.image.description="Download release from Gitlab project" \
  org.opencontainers.image.licenses="MIT" \
  org.opencontainers.image.revision=${REVISION} \
  org.opencontainers.image.source=https://github.com/dex4er/gitlab-ci-semver-labels \
  org.opencontainers.image.title=gitlab-ci-semver-labels \
  org.opencontainers.image.url=https://github.com/dex4er/gitlab-ci-semver-labels \
  org.opencontainers.image.vendor=dex4er \
  org.opencontainers.image.version=${VERSION}
